workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  if: '$CI_COMMIT_BRANCH == "master"'

experiment:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public/experiment
  artifacts:
    paths:
    - public/experiment
  if: '$CI_COMMIT_BRANCH == "Experiment2"'